export = [
    "Apparel",
    "Apparel>Accessories",
    "Apparel>Accessories>Bags & Packs",
    "Apparel>Accessories>Eyewear",
    "Apparel>Clothing",
    "Apparel>Clothing>Children's",
    "Apparel>Clothing>Costumes",
    "Entertainment",
    "Entertainment>TV & Movies",
    "Entertainment>TV & Movies>Cartoons",
    "Entertainment>TV & Movies>Comedy",
    "Entertainment>Music",
    "Entertainment>Music>Rock",
    "Entertainment>Music>Hip Hop",
];